sudo : true

language: node_js

node_js:
  - "8"

services:
  - mongodb

env:
  - CXX=g++-4.8

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

after_success:
  - cd $(./.ci_helper.sh name)
  - npm install
  - npm run test
