sudo : false

language: node_js

node_js:
  - "8"

services:
  - mongodb

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  - cd $(./.ci_helper.sh name)
  - npm install
  - npm run test
